immutable/imx-core-sdk

src/workflows/deposit/depositERC721.ts, src/workflows/withdrawal/completeERC20Withdrawal.ts, src/workflows/withdrawal/completeERC721Withdrawal.ts, src/workflows/withdrawal/completeEthWithdrawal.ts, src/workflows/withdrawal/prepareWithdrawal.ts, src/workflows/workflows.ts
Some spelling fixes and rearrange imports
=> code tidy and spelling

README.md
Fixes link to the docs website
=> Fix link to the docs website

README.md
fix: Clean up wording and clarify the currently supported rollups
Increase Clarity of Readme
=> fix: Clean up wording and clarify the currently supported rollups

README.md
* Add package-lock file to ensure the usage of stable dependencies versions.
* Add Codeclimate badge and local setup instructions.
=> Add local setup instructions and Codeclimate badge

CHANGELOG.md
Update change log for patch release
=> chore: update changelog [DX-928]

.github/dependabot.yml
To ensure the packages are up to date and protected against security vulnerabilities.
=> chore: enable Dependabot (DX-968)

README.md
Adding a badge to the README that shows the latest NPM version and also links to the NPM page.
None of the documentation links back to the NPM repo.
=> Add npm badge to README.

CHANGELOG.md, src/types/withdrawal.ts, src/workflows/withdrawal/completeERC20Withdrawal.ts, src/workflows/withdrawal/prepareWithdrawal.ts, src/workflows/workflows.ts
- add `prepareWithdrawalWorkflowWithSigner `
- deprecate `prepareWithdrawalWorkflow `
=> feat: add prepareWithdrawalWorkflowWithSigner 

package.json, rollup.config.js, yarn.lock
Currently we have [a build error](https://rollupjs.org/guide/en/#error-this-is-undefined), the reason for this is because Rollup replaces any `this` that is not inside a function or class with `undefined`.
The external dependencies, `@ethersproject/properties` and `@ethersproject/abstract-signer` are built this way. Our bundler is only complaining about code from another bundler. We can simply ignore this error, [as inspired by this](https://github.com/rollup/rollup/issues/1518#issuecomment-321875784), as it is out of our hands to fix. 
This has been tested with `yalc` and works as we would expect.
Before:
```bash
$ NODE_ENV=production rollup --config rollup.config.js
src/index.ts → dist/index.es.js, dist/index.cjs.js...
(!) `this` has been rewritten to `undefined` …
```
=> [DX-1215] Fix build error

src/ImmutableX.ts
Plural doesn't make sense as it gets public Stark keys for a single user.
To make the interface clearer.
=> [DX-1226] make getUsers singular

src/config/config.ts
Add config for sandbox to the new interface class.
The merge happened.
=> Update sandbox config, add ropsten config.

README.md
Add config examples for connecting to the sandbox environment.
Sandbox release soon.
=> [DX-1180] Add sandbox config info to README instructions.

src/exportContracts.ts
[DX-1236]
[DX-1236]: https://immutable.atlassian.net/browse/DX-1236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: expose IERC20 and IERC721 on Contracts namespace

src/workflows/registration.ts
This PR ensures that `.registerOffchain()` returns the expected type instead of a blank return.
Better DX
=> [DX-1246] Ensure registerOffchain() returns expected type

README.md
This PR makes warning for generating own signers more prominent.
See above
=> Make warning for generating own signers more prominent

.github/workflows/publish.yaml, CHANGELOG.md, README.md
This PR adds beta release capability and updates the changelog for unreleased changes.
Required for a beta release
=> Beta release support

examples/depositEth.ts
Add comment for expected amount value 
[DX-1308]
[DX-1308]: https://immutable.atlassian.net/browse/DX-1308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: add comment for expected amount value

.github/pull_request_template.md
Add documentation update checklist item to PR template
To ensure that changes/updates to the SDK are properly documented
=> Add docs update checklist item to PR template

CHANGELOG.md, examples/README.md
Update example readme to include exchange-transfers and nft-checkout-primary with moonpay.
Update changelog to include secondary-nft-checkout with moonpay
=> [No Jira] Update CHANGELOG.md and example README.md

examples/README.md, examples/cancelOrder.ts, examples/getOrder.ts, examples/listMints.ts, examples/listOrders.ts, examples/package.json
Adds code examples for listOrders, getOrder, and cancelOrder. Also removes unnecessary code from listMints and getMint.
listOrders:
```
examples % yarn list-orders
yarn run v1.22.19
$ ts-node -r dotenv/config listOrders.ts
listOrdersResponse {"result":[{"order_id":247576,"status":"filled","user":"0x50b675b88dd6ba67f8d3168fedac1f6217228bf7","sell":{"type":"ETH","data":{"token_address":"","decimals":18,"quantity":"7000000000000000","quantity_with_fees":"7210000000000000"}},"buy":{"type":"ERC721","data":{"token_id":"2","id":"0x75881df65e310c2b8306d7bd48cc003292d70660ffc0b9c7870bd324bb652a74","token_address":"0xcebaa2693cac6b801726d1096b2387a651d70326","quantity":"1","quantity_with_fees":"","properties":{"name":"2nd NFT","image_url":"https://gateway.pinata.cloud/ipfs/QmUWadE2EN45S2tGvZH9Dncdix …
```
=> Add examples for orders

examples/README.md, examples/getToken.ts, examples/getTrade.ts, examples/listTokens.ts, examples/listTrades.ts, examples/package.json
Adds get and list examples for tokens and trades. 
List trades:
```
examples % yarn list-trades
yarn run v1.22.19
$ ts-node -r dotenv/config listTrades.ts
listTradesResponse {"result":[{"transaction_id":2509799,"status":"success","a":{"order_id":247576,"token_type":"ETH","sold":"7000000000000000"},"b":{"order_id":164974,"token_type":"ERC721","token_id":"2","token_address":"0xcebaa2693cac6b801726d1096b2387a651d70326","sold":"1"},"timestamp":"2023-01-10T02:12:08.298059Z"}],"cursor":"eyJ0cmFuc2FjdGlvbl9pZCI6MjUwOTc5OSwic3RhdHVzIjoic3VjY2VzcyIsInBhcnR5X2Ffb3JkZXJfaWQiOjI0NzU3NiwicGFydHlfYV9ldGhlcl9rZXkiOiIweDUwYjY3NWI4OGRkNmJhNjdmOGQzMTY4ZmVkYWMxZjYyMTcyMjhiZjciLCJwYXJ0eV9hX3NvbGRfdG9rZW5fdHlwZSI6IkVUSCIsInBhcnR5X2Ffc29sZF90b2tlbl9pZCI6IiIsInBhcnR5X2Ffc29sZF90b2tlbl9hZGRyZXNzIjoiIiwicGFydHlfYV …
```
=> Add trade and token examples

examples/README.md, examples/listCollectionFilters.ts, examples/listCollections.ts, examples/package.json, examples/updateCollection.ts
Added examples for list collections, list collection filters, and update collection.
Support team's project to flesh out all core-sdk code examples.
NA
=> core-sdk examples for collections

openapi.json, src/api/domain/orders-api.ts, src/api/domain/trades-api.ts, src/api/domain/transfers-api.ts
Update the client API to accept auth token
* pulled openapi.json from prod, but only added the change needed for PassportImxProvider.
* All the typescript codes are generated.
=> [ID-469]Update the client api to accept authtoken

CHANGELOG.md
=> feat: added unreleased changelog for previous update

CHANGELOG.md, package.json
=> feat: Release 1.1.0

src/utils/stark/starkCurve.test.ts, src/utils/stark/starkCurve.ts
Fixed bug with grinding logic. 
See https://immutable.atlassian.net/browse/DX-2167
Updated the grinding logic to be same as in imx-sdk-js and also core-sdk-golang.
https://immutable.atlassian.net/browse/DX-2167
=> DX-2167: Fixed bug with grinding logic

CHANGELOG.md
Added Changelog in preparation for release.
DX-2167
=> DX-2167: Added changelog

openapi.json, src/api/domain/orders-api.ts, src/api/domain/trades-api.ts, src/api/domain/transfers-api.ts, src/api/models/order-v3.ts
Reflecting updates from the Orderbook openapi documentation
https://immutable.atlassian.net/browse/TD-803
=> TD-803 API docs update

src/api/models/get-signable-order-request-v3.ts, src/api/models/get-signable-order-response.ts, src/api/models/get-signable-trade-request.ts, src/api/models/get-signable-trade-response.ts, src/api/models/token-data.ts
Reflecting some missed updates from the Orderbook openapi documentation
https://immutable.atlassian.net/browse/TD-803
=> TD-803 - Some more missing API docs updates

src/config/config.ts
=> CORE-1838 update sandbox configs

CHANGELOG.md, package.json
The code for v1 order and trade deprecation is in `main` already. I was unaware we need to manually bump the package.json and changelog for this repo
=> [TD-999] version bump and changelog
