immutable/imx-core-sdk

CHANGELOG.md
src/types/index.ts
src/utils/stark/stark-key.test.ts
src/utils/stark/stark-key.ts

This PR generate the Stark Keys from **ethAddress** and **signature** .
* We need to change it in core-sdk because the starkkey generation is on Core-SDK.
* The existed function used signer to generate the starkKey. but signer doesn't existed in the L2Wallet(iframe)(it only exists outside of the iframe). in the L2Wallet we have only **EthAddress** and **SignedMessage**. so that's why we need to add this function from the core-sdk
* Returns the **path** as well, that is because we want to store it in the localStorage, and the path would be the key if I align to the current localstorage structure like the following screenshot:
It is the first PR from Wallet Team, so we don't know about the Process like:
* Should we bump the version
* Where should we update the changelog
* How to release the …

Generate Stark Keys From EthAddress and Signature

---

CHANGELOG.md
src/utils/index.ts
src/utils/stark/base-signer.ts
src/workflows/trades.ts
src/workflows/workflows.ts

* Introduces BaseSigner, a default implementation of the Stark L2Signer interface something like: `@ethers/Signer`.
* Add `createTradeWorkflowWithSigner` function to enable creating trade workflow with l2signer
* Not tight the workflow to the ways of how L2Wallet to sign the message.
* Allows having different l2Signer implementation which knows and defines the **signMessage** themselves.
* In that way, **core-sdk** would have it BaseSigner knows how to sign the message, also **wallet-sdk** would implement their own l2Wallet Signer to define how to **signMessage** 
* To avoid breaking change, we follow the release plan: https://imtbl.slack.com/archives/C035V01VBKL/p1656553279539269?thread_ts=1656486878.526449&cid=C035V01VBKL
* Tested the function from this imx-testing repo: …

Add function to enable create trade workflow with l2signer [wt-423]

---

CHANGELOG.md
src/utils/stark/base-signer.ts
src/workflows/registration.ts
src/workflows/workflows.ts

- Added `registerOffchainWithSigner` function to enable register offchain user with l2signer
- mark `registerOffchain` as deprecated
- `getAddress` method from BaseSigner
This is one of the series changes that we do to replace the **starkwallet** to **l2signer** to sign the message. 
the previous reference PR is: https://github.com/immutable/imx-core-sdk/pull/78
Tested the function from this **imx-testing** repo: https://github.com/immutable/imx-testing/pull/73

Add registerOffchainWithSigner function

---

CHANGELOG.md
src/workflows/burn.ts
src/workflows/workflows.ts

- Added `burnWithSigner` function to enable burn NFTs with l2signer
- mark `burn` as deprecated
This is one of the series changes that we do to replace the **starkwallet** to **l2signer** to sign the message. 
the previous reference PR is: https://github.com/immutable/imx-core-sdk/pull/78
Tested the function from this **imx-testing** repo: https://github.com/immutable/imx-testing/pull/78

Add burnWithSigner function

---

CHANGELOG.md
src/utils/stark/stark-key.ts

When I was using the `getStarkPublicKey` method to get my public key, I found the key I get is not the same as the first time generated. 
ex: the first time generated starts from '**0x**123456', but this starts from '**07**123456'
So I proposed this change to ensure every other time, when getting the stark public key, it always gets the same one as the first time generating stark key returns.
To avoid breaking changes also to better scope the function. added
the private `getStarkPublicKeyWithXCoordinate`

getStarkPublicKeyWithXCoordinate method returns the same as generateStarkWallet returns

---

src/workflows/registration.ts
src/workflows/trades.ts
src/workflows/workflows.ts

- registerOffchainWithSigner to use WalletConnection instead of isolated signers
- createTradeWithSigner to use WalletConnection instead of isolated signers
Following the last definitions on how the Wallets SDK outcome will look like, it was needed to update on Core SDK the function parameters to suit the Wallets SDK output.
Tests were also updated on **imx-testing** through this [PR](https://github.com/immutable/imx-testing/pull/80)

Updating functions to suit Wallets SDK WalletConnection object

---

CHANGELOG.md
src/workflows/workflows.ts

- Added `isRegisteredOnchainWithSigner` function to enable checking registration onchain with the Wallets SDK WalletConnection object
- mark `isRegisteredOnchain` as deprecated
This is one of the series changes that we do to replace the **starkwallet** to **l2signer** to sign the message.
Tests were also updated on **imx-testing** through this [PR](https://github.com/immutable/imx-testing/pull/81)

Add isRegisteredOnchainWithSigner workflow function

---

README.md

Adds a notice about the Core SDK interface being unstable
The Core SDK has many breaking public interface changes coming up in the next few weeks. This notice informs users about it.

Add a notice about the Core SDK interface being unstable

---

CHANGELOG.md
src/types/index.ts
src/workflows/registration.ts
src/workflows/workflows.ts

Changing the `L2Signer.getAddress` interface method to enable async implementations  
[We detected](https://immutable.atlassian.net/browse/WT-614) that it could be confusing for the partner which is integrating, to use getAddress methods in different ways regarding L1 and L2.
Today when the partner is integrating, and it is needed to retrieve L1 and L2 addresses, the following is done:
```ts
const walletConnection = [... Setting up and getting the connection obj from the Wallets SDK]
const l1Address = await walletConnection.l1Signer.getAddress();
const l1Address = walletConnection.l2Signer.getAddress();
```
We think the behaviour ideally should be the same, so we are changing that to: 
```ts
const walletConnection = [... Setting up and getting the connection obj from the Wallets SDK] …
```

Changed L2Signer interface to enable async getAddress implementations.

---

src/types/deposit.ts
src/types/index.ts
src/types/signable-withdrawal.ts
src/types/token.ts
src/types/withdrawal.ts
src/workflows/withdrawal/completeERC20Withdrawal.ts
src/workflows/withdrawal/completeERC721Withdrawal.ts
src/workflows/workflows.ts

this allows consumer to avoid having to import TokenType enum
[DX-1159]
[DX-1159]: https://immutable.atlassian.net/browse/DX-1159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: token type as string instead of enum

---

src/ImmutableX.ts
src/index.ts

This PR removes the API namespace. All generated types will be at the top level, each request type will have to be imported individually to be used.
Cleaner developer experience.

[DX-1218] Remove API namespace

---

package.json
yarn.lock

This PR fixes the `yarn i` warnings from missing peer deps. 
We want to fix all errors/warnings for v1.

[DX-1224] Fix peer dependency warnings

---

Makefile

Configure the Makefile to work with the new Sandbox OpenAPI spec, which should generate the SDK with new base URLs too.
Ropsten spec should be deprecated soon.
Code generation was not run with this PR. The diff would be very large filled with auto-generated code.

[DX-1227] Update Makefile, use sandbox OpenAPI spec.

---

src/index.ts

This PR removes the `Utils` namespace.
Not required as their are only a few methods.
Not used in any workflows or tests.

[DX-1237] Remove Utils namespace

---

examples/README.md
examples/depositNft.ts
examples/package.json

Adds code example for depositing NFT
```
examples % yarn deposit-nft
yarn run v1.22.19
$ ts-node -r dotenv/config depositNft.ts
depositResponse {
type: 2,
chainId: 5,
nonce: 45,
maxPriorityFeePerGas: BigNumber { _hex: '0x59682f00', _isBigNumber: true },
maxFeePerGas: BigNumber { _hex: '0x596863a4', _isBigNumber: true },
gasPrice: null,
gasLimit: BigNumber { _hex: '0x01c8be', _isBigNumber: true },
to: '0x7917eDb51ecD6CdB3F9854c3cc593F33de10c623',
value: BigNumber { _hex: '0x00', _isBigNumber: true },
data: '0xae1cdde60468fbbca8b615da71d2bc823314885dddab97f9dc9d595c93c087bd8299a1ea031c7813c8a3a7c84641031c30945c54c7c65200147b2b68ae8b84c2e97be4da000000000000000000000000000000000000000000000000000000000036a47a0000000000000000000000000000000000000000000000000000000000000010',
accessList: [], …
```

Add deposit NFT example

---

examples/README.md
examples/getMint.ts
examples/listMints.ts
examples/package.json

Adds get mint and list mints examples
Get mint:
```
examples % yarn get-mint
yarn run v1.22.19
$ ts-node -r dotenv/config getMint.ts
getMintResponse [{"transaction_id":391205,"status":"success","user":"0x6c660d56f4d5d926341d5d8b9a855a15095457fa","token":{"type":"ERC721","data":{"token_id":"1","id":"0x99374278b18c3f250911af5c1c6da58b1fc1f5dd95f0ac1db071809b61c43a4d","token_address":"0xcebaa2693cac6b801726d1096b2387a651d70326","quantity":"1","quantity_with_fees":""}},"timestamp":"2022-11-10T03:33:39.872898Z"}]
✨  Done in 2.28s.
```
List mints:
```
examples % yarn list-mints
yarn run v1.22.19
$ ts-node -r dotenv/config listMints.ts
listMintsResponse {"result":[{"transaction_id":391207,"status":"success","user":"0x6c660d56f4d5d926341d5d8b9a855a15095457fa","token":{"type":"ERC721","data":{"toke …
```

Add get mint and list mints examples

---

src/ImmutableX.ts

Removing unused method from the public interface.

NOJIRA: Remove getMintStatus from the public API

---

README.md

v1.0.1 has a critical fix for the `grindkey` function. All users should upgrade as soon as possible.
https://immutable.atlassian.net/browse/DX-1708
Critical bug fix was found and patched.

Add warning section to README to tell users to upgrade to v1.0.1.

---

openapi.json
src/api/domain/exchanges-api.ts

* All code is generated
* changed `x-imx-eth-address` and `x-imx-eth-signature` to be optional
* Added optional `Authorization` header

Update Exchange Transfer to allow Authorization header

---

src/config/config.test.ts
src/config/config.ts

This is a **non breaking change** as we default to the Core SDK identifier for this change. It will not affect existing configs.

[DX-2019] Add `sdkVersion` param to config

---

openapi.json
package.json
src/api/domain/trades-api.ts

Add support for `v3/trade/{id}` and deprecate `v1/trade/{id}`.
https://immutable.atlassian.net/browse/TD-803
Keep in line with Traders supported endpoints.

TD-803 - Update supported get trade endpoints

---

CHANGELOG.md
package.json

The version numbers in both package.json and CHANGELOG.md were mistakenly updated to 2.0.3. This commit reverts the version back to 2.0.2 in package.json, and changes the version title in the CHANGELOG.md to "Unreleased". The updates made were premature and the version number should only be changed upon official release.

TD-503 Revert version number in package.json and CHANGELOG.md

---

CHANGELOG.md
package.json

This commit changes the version of the project from 2.0.2 to 2.1.0 in both the package.json and the CHANGELOG.md files. The 'unreleased' tag in the changelog is also updated to reflect the new version. This change is made to mark the completion of new features and enhancements for the 2.1.0 release.

TD-803 Update version to 2.1.0 in changelog and package.json

---

CHANGELOG.md
package.json
src/ImmutableX.ts

Rerouting sunsetted v1s to v3 last endpoint left out was getTrade (workflow)

feat: TD-917 reroute getTrade to getTradeV3

---

CHANGELOG.md
package.json
yarn.lock

Adding missing documentation for previous commit + updating ethers and core-sdk version.
Resolves: [CORE-1838]
[CORE-1838]: https://immutable.atlassian.net/browse/CORE-1838?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CORE-1838 Update docs, version and ethers to enable sepolia integration
